server:
  port: 9696
  max-http-header-size: 10000000 
spring:
  application:
    name: AIGOU-COMMON
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
